# Site settings
title: Fun with Kernel and Web
header-img: "img/facebook.jpg"
tagline: "cn"  
description: "settings"  
baseurl: ""
url: "http://fuzhli"  

# About/contact
owner: 
  name: "fuzhli"
  email: fuzhli@hotmail.com
  bio: "内核业余爱好者"

# Data
gavatar: http://dreamofbook.qiniudn.com/Az..png
favicon: img/favicon.png

douban_username:  fuzhli
twitter_username: fuzhli
github_username: fuzhli
facebook_username: fuzhli
weibo_username: 川陀农夫
zhihu_username: 川陀农夫

# Build settings  
# use Github Flavored Markdown !important  
# document: http://jekyllrb.com/docs/configuration/#kramdown  
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 8
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
relative_permalinks: true

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: Asia/Shanghai

# Defaults for posts
defaults:
  -
    scope: 
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "fuzhli"
      header-img: "img/facebook.jpg" # We don't want posts without a header image, that whould mean white on white

# Comments 
comments :
  provider : duoshuo
  duoshuo :
    short_name : fuzhli
  disqus :
      short_name : fuzhli

# Analytics and webmaster tools stuff goes here
google_analytics: 
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in footer navigation
